### ISSUE TITLE
lmpatch issues/Text display issues

### ISSUE THREAD

**Issue by DarkPulse** [pmrowla/pylivemaker#8] opened 2019-06-16 20:30 UTC
Just as a followup, now that I got it properly working and patching, two problems:

1. lmpatch will fail if you are not patching on the same drive as your Python installation. In my case, the Python install is on C, but the extracted content is on I.

```
Traceback (most recent call last):
  File "c:\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36-32\Scripts\lmpatch.exe\__main__.py", line 9, in <module>
  File "c:\python36-32\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python36-32\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python36-32\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python36-32\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python36-32\lib\site-packages\livemaker\patch.py", line 115, in lmpat
ch
    raise e
  File "c:\python36-32\lib\site-packages\livemaker\patch.py", line 110, in lmpat
ch
    tmpfile_path.rename(exe_path)
  File "c:\python36-32\lib\pathlib.py", line 1287, in rename
    self._accessor.rename(self, target)
  File "c:\python36-32\lib\pathlib.py", line 393, in wrapped
    return strfunc(str(pathobjA), str(pathobjB), *args)
OSError: [WinError 17] The system cannot move the file to a different disk drive
: 'C:\\Users\\DARKPU~1\\AppData\\Local\\Temp\\tmphjb02bnb' -> 'game.exe'
```

Making a temporary copy in the C drive let lmpatch do its work without issue.

2. Text inserted is in full-width latin letters, which will seriously limit translation potential. These need to get converted to half-width somehow if we are to have any success without seriously crippling translation by being forced into brevity. Assuming, of course, LiveMaker is even capable of half-width latin letters.

![image](https://user-images.githubusercontent.com/5454684/59569143-699b9500-9053-11e9-861e-0b4a21f8599e.png)

This is approximately half of the actual translation, which is:

> "Phew～ I'm so worn-out today～ How long am I gonna keep working at this job...? All I want to do is be an architect, but nobody wants to hire me until I've got all the secondary qualifications."

Of note, the game will still display things just fine across multiple boxes. It didn't cut the line and go to the next dialogue box in the script, it actually displayed the rest of it on the same box before continuing to the next one.

A potential workaround would be to **_INSERT_** extra text boxes by breaking up such longer boxes into multiple, shorter ones, but it still would look very fat and widened and not all that pleasant. Better control would require conscious box-breaking control like that, or a more natural width for latin letters.

**Comment by pmrowla** [comment] 2019-06-17 00:12
> 1. lmpatch will fail if you are not patching on the same drive as your Python installation.

This is a python limitation with the os/pathlib `rename` functions and expected behavior as lmpatch is currently written. But it looks like `shutil.move` instead of `rename` would get around this, so I'll make a note to maybe change this in a future release.

> 2. Text inserted is in full-width latin letters

pylivemaker inserts whatever text codepoints are given by the user, so for latin characters it should be inserting the half-width characters and not the full-width variants, unless your text editor is actually using the full-width codepoints as well.

But yeah, I ran into the same issue when I was playing around with my test AGLS patch. Even if livemaker is given a script with half-width latin characters it renders them all with the full-width spacing. I looked into this a little bit, and I'm pretty sure this is a font kerning/rendering issue and not a text encoding issue.

When livemaker loads fonts it does the following:

1. Load every windows system font that is flagged as supporting Shift JIS (actually windows CP932)
2. Set the default windows font as the default font for livemaker (this is essentially always going to be MS Gothic)

As far as I can tell, when livemaker renders latin characters using MS Gothic they will always show up with the full-width spacing. It's possible that forcing livemaker to use a different font would fix the latin half-width rendering issues, but I haven't looked any deeper than this into the livemaker engine font handling code.

**Comment by DarkPulse** [comment] 2019-06-17 21:49
Hmm, okay, that'd explain why the font is larger if it's just blindly taking that and assuming fullwidth, and short of fixing the kerning or replacing it with a different font that LiveMaker will accept, not sure what else could really be done about that. Like I said, even if I "add" extra messageboxes (presumably I could do that just by adding a new paragraph block and ending it with the \<PG\> tag like the rest of them), the fullwidth font definitely makes it less nice to read.

Hopefully you've got a solution relatively soon, I'm out of work in about another week's time and then got approximately 2 1/2 months of holiday. Need some projects to dig into during this time off. :stuck_out_tongue:

**Comment by LioMajor** [comment] 2019-06-20 23:59
@DarkPulse

In LiveMaker3 for japanese games, the font uses a fixed size and it's possible to align charts properly.

Most likely you will have to patch at this three files to disable it:

メッセージボックス作成.lsb for new messages all " MesNew " 's

<Array Name="__ARG_166__">
	<Param Name="____arg" Calc="" Type="1">
		<Flag Name="">TRUE</Flag>
	</Param>
</Array>

> change it to false

And ノベルシステム\シナリオ回想\初期化.lsb

<Array Name="__ARG_166__"></Array>

to

<Array Name="__ARG_166__">
	<Param Name="____arg" Calc="" Type="1">
		<Flag Name="">FALSE</Flag>
	</Param>
</Array>

the same for ノベルシステム\メッセージボックス\プレビューメニュー処理.lsb

Older LiveMaker games doesn't have ARG_166, until now, i don't know a solution
for them and would be happy if someone knows what to change.

**Comment by LioMajor** [comment] 2019-06-21 00:00
@DarkPulse

In LiveMaker3 for japanese games, the font uses a fixed size and it's possible to align charts properly.

Most likely you will have to patch at this three files to disable it:

メッセージボックス作成.lsb for new messages all " MesNew " 's
[code]
<Array Name="__ARG_166__">
	<Param Name="____arg" Calc="" Type="1">
		<Flag Name="">TRUE</Flag>
	</Param>
</Array>
[/code]
> change it to false

And ノベルシステム\シナリオ回想\初期化.lsb
[code]
<Array Name="__ARG_166__"></Array>

to

<Array Name="__ARG_166__">
	<Param Name="____arg" Calc="" Type="1">
		<Flag Name="">FALSE</Flag>
	</Param>
</Array>
[/code]
the same for ノベルシステム\メッセージボックス\プレビューメニュー処理.lsb

Older LiveMaker games doesn't have ARG_166, until now, i don't know a solution
for them and would be happy if someone knows what to change.

**Comment by LioMajor** [comment] 2019-06-21 00:05
@DarkPulse

In LiveMaker3 for japanese games, the font uses a fixed size and it's possible to align charts properly.

Most likely you will have to patch at this three files to disable it:

メッセージボックス作成.lsb for new messages all " MesNew " 's
```
<Array Name="__ARG_166__">
	<Param Name="____arg" Calc="" Type="1">
		<Flag Name="">TRUE</Flag>
	</Param>
</Array>
```
change it to false

And ノベルシステム\シナリオ回想\初期化.lsb
```
<Array Name="__ARG_166__"></Array>

to

<Array Name="__ARG_166__">
	<Param Name="____arg" Calc="" Type="1">
		<Flag Name="">FALSE</Flag>
	</Param>
</Array>
```
the same for ノベルシステム\メッセージボックス\プレビューメニュー処理.lsb

Older LiveMaker games doesn't have ARG_166, until now, i don't know a solution
for them and would be happy if someone knows what to change.

**Comment by DarkPulse** [comment] 2019-06-21 02:19
@LioMajor I'm not sure if the game I'm trying to do this with is LiveMaker 3 or not. It's not using XML stuff, and the version inside the scenario scripts is 102, though, so I'm presuming not.

**Comment by LioMajor** [comment] 2019-06-21 03:33
@DarkPulse 
Yes, it's LiveMaker3. Example:
unpatched:
![unpatched](https://user-images.githubusercontent.com/591183/59895757-0a88a800-93e6-11e9-904a-9d37c93e6cc8.PNG)
patched:
![patched](https://user-images.githubusercontent.com/591183/59895768-11afb600-93e6-11e9-8503-41506457af8a.PNG)

**Comment by pmrowla** [comment] 2019-06-21 03:38
@LioMajor this is good to know, thanks. Although there's no easy way to patch those values with pylivemaker at the moment. The parameter objects are exposed as python objects through the pylivemaker API, but you'd have to write your own script or do it by hand through the python console to actually modify the boolean flag values.

**Comment by LioMajor** [comment] 2019-06-21 04:20
If tinfoil irl (py2 + bs4) works for you, it would be a solution until pylivemaker does it too.

**Comment by DarkPulse** [comment] 2019-06-21 04:38
@LioMajor The only MesNew labeled stuff I found in those was these inside メッセージボックス作成.lsb:

`8:     MesNew "メッセージボックス" "メッセージボックス土台" 20 12 GetProp("メッセージボックス土台", 5) - 20 - 20 GetProp("メッセージボックス土台", 6) - 12 - 10  1100   StatusFontName 22 0 0 16711680 0 16776960 1  0 "ノベルシステム\メッセージボックス\再生中.lsc" "ノベルシステム\メッセージボックス\イベント.lsc"     "ノベルシステム\メッセージボックス\右クリック時.lsc"    "ノベルシステム\メッセージボックス\終了.lsc" "ノベルシステム\メッセージボックス\リンク.lsc" 1 4 0   "ノベルシステム\メッセージボックス\再生開始.lsc"  "ノベルシステム\メッセージボックス\アイドル時.lsc"     14075569 0 2    0    1`

`36: MesNew "メッセージボックス" "メッセージボックス土台" 20 12 GetProp("メッセージボックス土台", 5) - 20 - 20 GetProp("メッセージボックス土台", 6) - 12 - 10  1100   StatusFontName 22 0 0 16711680 0 16776960 1  0 "ノベルシステム\メッセージボックス\再生中.lsc" "ノベルシステム\メッセージボックス\イベント.lsc"     "ノベルシステム\メッセージボックス\右クリック時.lsc"    "ノベルシステム\メッセージボックス\終了.lsc" "ノベルシステム\メッセージボックス\リンク.lsc" 1 4 0   "ノベルシステム\メッセージボックス\再生開始.lsc"  "ノベルシステム\メッセージボックス\アイドル時.lsc"     14075569 0 2    0    1`

I didn't see anything remotely looking like what you pasted.

**Comment by LioMajor** [comment] 2019-06-21 04:46
If you give me the 3 files i mentioned, i can check if i can patch them for you.

**Comment by DarkPulse** [comment] 2019-06-21 14:05
@LioMajor Sure, here you go. To get around the upload restrictions, rename the extension to .7z, I didn't want filenames getting clobbered.

[GameFiles.zip](https://github.com/pmrowla/pylivemaker/files/3314762/GameFiles.zip)

I'm probably just missing some kind of step here, so if you do do this, just walk me through the process briefly. This guy wrote about 40 games using this engine, so it'd be nice to get them all translated. Once I know what to do I can pretty much manage it on my own barring something unexpected showing up, but here I can't tell if I'm just not doing a step right or if the game really isn't a LM3 game,

But it goes without saying that if one of them can work with this method, likely all of them by this guy are done the exact same way.

**Comment by LioMajor** [comment] 2019-06-21 21:30
@DarkPulse i decrypted your files, but sadly it is an older game and it seems to be LiveMaker2 (around 2009/2010) and there is no ARG_166. Currently i don't know how to patch it, because if i make changes and add extra lines, it will break starting the game. It's like i mentioned before, i'm looking myself for a solution for this. If someone else has and idea or if i find it myself, i'll inform you. Sorry mate.

**Comment by DarkPulse** [comment] 2019-06-21 22:37
So then I was right and he wasn't making it with LM3. That's a shame, was a bit hopeful, but I figured that was the case when I couldn't find anything like what you'd found.

**Comment by pmrowla** [comment] 2019-07-30 04:47
Closing this as the cross-drive copy issue should be resolved now

**Closed by pmrowla** 2019-07-30 04:47 UTC
