### ISSUE TITLE
insertcsv fails when injecting vocals

### ISSUE THREAD

**Issue by LioMajor** [pmrowla/pylivemaker#53] opened 2020-05-09 11:41 UTC
* pylivemaker version: 09-05-2020
* Python version: 3.7
* Operating System: Win10

insertcsv fails when injecting vocals.

Traceback (most recent call last):
  File "C:\python\Scripts\lmlsb-script.py", line 11, in <module>
    load_entry_point('pylivemaker==1.0.0.dev0', 'console_scripts', 'lmlsb')()
  File "c:\python\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python\lib\site-packages\click-7.0-py3.7.egg\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python\lib\site-packages\pylivemaker-1.0.0.dev0-py3.7.egg\livemaker\cli\lmlsb.py", line 1288, in insertcsv
    translated, untranslated = _patch_csv_text(lsb, lsb_file, csv_data, verbose)
  File "c:\python\lib\site-packages\pylivemaker-1.0.0.dev0-py3.7.egg\livemaker\cli\lmlsb.py", line 1247, in _patch_csv_text
    lsb.replace_text(text_objects)
  File "c:\python\lib\site-packages\pylivemaker-1.0.0.dev0-py3.7.egg\livemaker\lsb\lmscript.py", line 548, in replace_text
    self.replace_text_blocks(new_objs["text"])
  File "c:\python\lib\site-packages\pylivemaker-1.0.0.dev0-py3.7.egg\livemaker\lsb\lmscript.py", line 575, in replace_text_blocks
    scenario.replace_text_blocks(tmp_blocks)
  File "c:\python\lib\site-packages\pylivemaker-1.0.0.dev0-py3.7.egg\livemaker\lsb\novel.py", line 917, in replace_text_blocks
    new_ch = TWdChar(ch=ch, **d)
  File "c:\python\lib\site-packages\pylivemaker-1.0.0.dev0-py3.7.egg\livemaker\lsb\novel.py", line 258, in __init__
    raise BadLnsError("'{}' is not a valid CP932 character".format(ch))
livemaker.exceptions.BadLnsError: 'ö' is not a valid CP932 character

**Comment by pmrowla** [comment] 2020-05-09 11:59
assuming the desired behavior here is to to just convert it to an `o`?

**Comment by pmrowla** [comment] 2020-05-09 12:00
or just continue replacing everything else, and warn about the ones with invalid chars?

**Comment by LioMajor** [comment] 2020-05-09 12:04
The replacement woud go to ' oe ', but that's not very readable and takes extra space
what might exceed the line / block.

**Comment by pmrowla** [comment] 2020-05-09 12:08
The issue is that `ö` doesn't exist in CP932 though

**Comment by LioMajor** [comment] 2020-05-09 12:17
That's sad, a conversion would do well.

I guess öÖ > oO , äÄ > aA , üÜ > uU , ß > ss would be the work around.

At least better than oe, ae , ue...

**Comment by pmrowla** [comment] 2020-05-09 12:21
As far as allowing characters that don't exist in shift-jis/CP932 goes, we cannot do that right now because it's an LM engine limitation. We can only use characters from: https://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP932.TXT

Issue/discussion regarding making the engine support other encodings (utf-8) already exists (#14)

As far as the exception raised during patching goes, replacement is one thing, but I think we should maybe not do that automatically for now, given that people may have differing opinions on what replacements to use (`oe` vs `o`).

I think the short term thing to do is just output a warning message saying something like 
```
Skipping block containing invalid character "ö": pylm:text:<block id> "<translated_text>"
```
and then continuing w/trying to patch the rest of the blocks from CSV

**Comment by Stefan311** [comment] 2020-05-09 12:44
Do you think it would be possible to patch the LM engine to UTF8 or UTF16?
Do you know what delphi version is used for compilation of the LM engine?
The later versions of delphi using 16bit unicode (UTF16?) as default string implementation.
So maybe there is a CP932 to unicode conversion somewhere in the LSB loader.

**Comment by LioMajor** [comment] 2020-05-09 12:51
I doubt it, i also hoped that there would be a way to convert LM2 to LM3 to disable letterspacing :/

**Comment by pmrowla** [comment] 2020-05-09 13:01
> Do you think it would be possible to patch the LM engine to UTF8 or UTF16?
> Do you know what delphi version is used for compilation of the LM engine?
> The later versions of delphi using 16bit unicode (UTF16?) as default string implementation.
> So maybe there is a CP932 to unicode conversion somewhere in the LSB loader.

it's delphi 5, there is no UTF16 support

**Comment by pmrowla** [comment] 2020-05-09 13:15
honestly usually when I start looking into it, I usually end up thinking it would better to just write something that auto-ports LM games to renpy or some other modern engine.

**Comment by Stefan311** [comment] 2020-05-09 13:24
Delphi 5? Really? I used Delphi 3, 5 and later 2009, and i really liked it. But that's many years ago...

**Comment by pmrowla** [comment] 2020-05-09 14:37
closing this as the exception is fixed to now be warning/continue. discussion about unicode support can go in the existing issue #14

**Closed by pmrowla** 2020-05-09 14:37 UTC
